{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "54477342-6d5c-4e3e-b846-e5a6c56478c1",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "Attaching package: 'scales'\n",
      "\n",
      "\n",
      "The following object is masked from 'package:purrr':\n",
      "\n",
      "    discard\n",
      "\n",
      "\n",
      "The following object is masked from 'package:readr':\n",
      "\n",
      "    col_factor\n",
      "\n",
      "\n",
      " 1. run of importance source...\n",
      "\n",
      " 2. run of importance source...\n",
      "\n",
      " 3. run of importance source...\n",
      "\n",
      " 4. run of importance source...\n",
      "\n",
      " 5. run of importance source...\n",
      "\n",
      " 6. run of importance source...\n",
      "\n",
      " 7. run of importance source...\n",
      "\n",
      " 8. run of importance source...\n",
      "\n",
      " 9. run of importance source...\n",
      "\n",
      " 10. run of importance source...\n",
      "\n",
      " 11. run of importance source...\n",
      "\n",
      " 12. run of importance source...\n",
      "\n",
      " 13. run of importance source...\n",
      "\n",
      "After 13 iterations, +3.2 secs: \n",
      "\n",
      " confirmed 5 attributes: Age, Hb, HCT, RBC, RHR;\n",
      "\n",
      " rejected 23 attributes: AV, CAD_Type, CI, CK, CO and 18 more;\n",
      "\n",
      " still have 17 attributes left.\n",
      "\n",
      "\n",
      " 14. run of importance source...\n",
      "\n",
      " 15. run of importance source...\n",
      "\n",
      " 16. run of importance source...\n",
      "\n",
      " 17. run of importance source...\n",
      "\n",
      "After 17 iterations, +3.9 secs: \n",
      "\n",
      " confirmed 1 attribute: Diabetes;\n",
      "\n",
      " rejected 4 attributes: AOs, el, LVPWd, TG;\n",
      "\n",
      " still have 12 attributes left.\n",
      "\n",
      "\n",
      " 18. run of importance source...\n",
      "\n",
      " 19. run of importance source...\n",
      "\n",
      " 20. run of importance source...\n",
      "\n",
      "After 20 iterations, +4.4 secs: \n",
      "\n",
      " confirmed 2 attributes: EA, Gender;\n",
      "\n",
      " still have 10 attributes left.\n",
      "\n",
      "\n",
      " 21. run of importance source...\n",
      "\n",
      " 22. run of importance source...\n",
      "\n",
      " 23. run of importance source...\n",
      "\n",
      " 24. run of importance source...\n",
      "\n",
      "After 24 iterations, +5 secs: \n",
      "\n",
      " confirmed 2 attributes: BMI, Smoking;\n",
      "\n",
      " still have 8 attributes left.\n",
      "\n",
      "\n",
      " 25. run of importance source...\n",
      "\n",
      " 26. run of importance source...\n",
      "\n",
      " 27. run of importance source...\n",
      "\n",
      "After 27 iterations, +5.4 secs: \n",
      "\n",
      " confirmed 1 attribute: Height;\n",
      "\n",
      " still have 7 attributes left.\n",
      "\n",
      "\n",
      " 28. run of importance source...\n",
      "\n",
      " 29. run of importance source...\n",
      "\n",
      " 30. run of importance source...\n",
      "\n",
      " 31. run of importance source...\n",
      "\n",
      " 32. run of importance source...\n",
      "\n",
      " 33. run of importance source...\n",
      "\n",
      "After 33 iterations, +6.3 secs: \n",
      "\n",
      " confirmed 1 attribute: es;\n",
      "\n",
      " still have 6 attributes left.\n",
      "\n",
      "\n",
      " 34. run of importance source...\n",
      "\n",
      " 35. run of importance source...\n",
      "\n",
      " 36. run of importance source...\n",
      "\n",
      " 37. run of importance source...\n",
      "\n",
      " 38. run of importance source...\n",
      "\n",
      " 39. run of importance source...\n",
      "\n",
      " 40. run of importance source...\n",
      "\n",
      " 41. run of importance source...\n",
      "\n",
      " 42. run of importance source...\n",
      "\n",
      " 43. run of importance source...\n",
      "\n",
      " 44. run of importance source...\n",
      "\n",
      "After 44 iterations, +8 secs: \n",
      "\n",
      " confirmed 1 attribute: Weight;\n",
      "\n",
      " still have 5 attributes left.\n",
      "\n",
      "\n",
      " 45. run of importance source...\n",
      "\n",
      " 46. run of importance source...\n",
      "\n",
      " 47. run of importance source...\n",
      "\n",
      " 48. run of importance source...\n",
      "\n",
      " 49. run of importance source...\n",
      "\n",
      " 50. run of importance source...\n",
      "\n",
      " 51. run of importance source...\n",
      "\n",
      " 52. run of importance source...\n",
      "\n",
      " 53. run of importance source...\n",
      "\n",
      " 54. run of importance source...\n",
      "\n",
      " 55. run of importance source...\n",
      "\n",
      " 56. run of importance source...\n",
      "\n",
      " 57. run of importance source...\n",
      "\n",
      " 58. run of importance source...\n",
      "\n",
      " 59. run of importance source...\n",
      "\n",
      " 60. run of importance source...\n",
      "\n",
      " 61. run of importance source...\n",
      "\n",
      " 62. run of importance source...\n",
      "\n",
      " 63. run of importance source...\n",
      "\n",
      " 64. run of importance source...\n",
      "\n",
      " 65. run of importance source...\n",
      "\n",
      " 66. run of importance source...\n",
      "\n",
      " 67. run of importance source...\n",
      "\n",
      " 68. run of importance source...\n",
      "\n",
      " 69. run of importance source...\n",
      "\n",
      " 70. run of importance source...\n",
      "\n",
      " 71. run of importance source...\n",
      "\n",
      " 72. run of importance source...\n",
      "\n",
      " 73. run of importance source...\n",
      "\n",
      " 74. run of importance source...\n",
      "\n",
      " 75. run of importance source...\n",
      "\n",
      " 76. run of importance source...\n",
      "\n",
      " 77. run of importance source...\n",
      "\n",
      " 78. run of importance source...\n",
      "\n",
      " 79. run of importance source...\n",
      "\n",
      " 80. run of importance source...\n",
      "\n",
      " 81. run of importance source...\n",
      "\n",
      " 82. run of importance source...\n",
      "\n",
      " 83. run of importance source...\n",
      "\n",
      " 84. run of importance source...\n",
      "\n",
      " 85. run of importance source...\n",
      "\n",
      " 86. run of importance source...\n",
      "\n",
      " 87. run of importance source...\n",
      "\n",
      " 88. run of importance source...\n",
      "\n",
      " 89. run of importance source...\n",
      "\n",
      " 90. run of importance source...\n",
      "\n",
      " 91. run of importance source...\n",
      "\n",
      " 92. run of importance source...\n",
      "\n",
      " 93. run of importance source...\n",
      "\n",
      " 94. run of importance source...\n",
      "\n",
      " 95. run of importance source...\n",
      "\n",
      " 96. run of importance source...\n",
      "\n",
      " 97. run of importance source...\n",
      "\n",
      " 98. run of importance source...\n",
      "\n",
      " 99. run of importance source...\n",
      "\n",
      " 100. run of importance source...\n",
      "\n",
      " 101. run of importance source...\n",
      "\n",
      " 102. run of importance source...\n",
      "\n",
      " 103. run of importance source...\n",
      "\n",
      " 104. run of importance source...\n",
      "\n",
      " 105. run of importance source...\n",
      "\n",
      " 106. run of importance source...\n",
      "\n",
      " 107. run of importance source...\n",
      "\n",
      " 108. run of importance source...\n",
      "\n",
      " 109. run of importance source...\n",
      "\n",
      " 110. run of importance source...\n",
      "\n",
      " 111. run of importance source...\n",
      "\n",
      " 112. run of importance source...\n",
      "\n",
      " 113. run of importance source...\n",
      "\n",
      " 114. run of importance source...\n",
      "\n",
      " 115. run of importance source...\n",
      "\n",
      " 116. run of importance source...\n",
      "\n",
      " 117. run of importance source...\n",
      "\n",
      " 118. run of importance source...\n",
      "\n",
      " 119. run of importance source...\n",
      "\n",
      " 120. run of importance source...\n",
      "\n",
      " 121. run of importance source...\n",
      "\n",
      " 122. run of importance source...\n",
      "\n",
      " 123. run of importance source...\n",
      "\n",
      " 124. run of importance source...\n",
      "\n",
      " 125. run of importance source...\n",
      "\n",
      " 126. run of importance source...\n",
      "\n",
      " 127. run of importance source...\n",
      "\n",
      " 128. run of importance source...\n",
      "\n",
      " 129. run of importance source...\n",
      "\n",
      " 130. run of importance source...\n",
      "\n",
      " 131. run of importance source...\n",
      "\n",
      " 132. run of importance source...\n",
      "\n",
      " 133. run of importance source...\n",
      "\n",
      " 134. run of importance source...\n",
      "\n",
      " 135. run of importance source...\n",
      "\n",
      " 136. run of importance source...\n",
      "\n",
      " 137. run of importance source...\n",
      "\n",
      " 138. run of importance source...\n",
      "\n",
      " 139. run of importance source...\n",
      "\n",
      " 140. run of importance source...\n",
      "\n",
      " 141. run of importance source...\n",
      "\n",
      " 142. run of importance source...\n",
      "\n",
      " 143. run of importance source...\n",
      "\n",
      " 144. run of importance source...\n",
      "\n",
      " 145. run of importance source...\n",
      "\n",
      " 146. run of importance source...\n",
      "\n",
      " 147. run of importance source...\n",
      "\n",
      " 148. run of importance source...\n",
      "\n",
      " 149. run of importance source...\n",
      "\n",
      " 150. run of importance source...\n",
      "\n",
      " 151. run of importance source...\n",
      "\n",
      " 152. run of importance source...\n",
      "\n",
      " 153. run of importance source...\n",
      "\n",
      " 154. run of importance source...\n",
      "\n",
      " 155. run of importance source...\n",
      "\n",
      " 156. run of importance source...\n",
      "\n",
      " 157. run of importance source...\n",
      "\n",
      " 158. run of importance source...\n",
      "\n",
      " 159. run of importance source...\n",
      "\n",
      " 160. run of importance source...\n",
      "\n",
      " 161. run of importance source...\n",
      "\n",
      " 162. run of importance source...\n",
      "\n",
      " 163. run of importance source...\n",
      "\n",
      " 164. run of importance source...\n",
      "\n",
      " 165. run of importance source...\n",
      "\n",
      " 166. run of importance source...\n",
      "\n",
      " 167. run of importance source...\n",
      "\n",
      " 168. run of importance source...\n",
      "\n",
      " 169. run of importance source...\n",
      "\n",
      " 170. run of importance source...\n",
      "\n",
      " 171. run of importance source...\n",
      "\n",
      "After 171 iterations, +27 secs: \n",
      "\n",
      " rejected 1 attribute: AOasc;\n",
      "\n",
      " still have 4 attributes left.\n",
      "\n",
      "\n",
      " 172. run of importance source...\n",
      "\n",
      " 173. run of importance source...\n",
      "\n",
      " 174. run of importance source...\n",
      "\n",
      " 175. run of importance source...\n",
      "\n",
      " 176. run of importance source...\n",
      "\n",
      " 177. run of importance source...\n",
      "\n",
      " 178. run of importance source...\n",
      "\n",
      " 179. run of importance source...\n",
      "\n",
      " 180. run of importance source...\n",
      "\n",
      " 181. run of importance source...\n",
      "\n",
      " 182. run of importance source...\n",
      "\n",
      " 183. run of importance source...\n",
      "\n",
      " 184. run of importance source...\n",
      "\n",
      " 185. run of importance source...\n",
      "\n",
      " 186. run of importance source...\n",
      "\n",
      " 187. run of importance source...\n",
      "\n",
      " 188. run of importance source...\n",
      "\n",
      " 189. run of importance source...\n",
      "\n",
      " 190. run of importance source...\n",
      "\n",
      " 191. run of importance source...\n",
      "\n",
      " 192. run of importance source...\n",
      "\n",
      " 193. run of importance source...\n",
      "\n",
      " 194. run of importance source...\n",
      "\n",
      " 195. run of importance source...\n",
      "\n",
      " 196. run of importance source...\n",
      "\n",
      " 197. run of importance source...\n",
      "\n",
      " 198. run of importance source...\n",
      "\n",
      " 199. run of importance source...\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Boruta confirmed features:\n",
      " [1] \"Diabetes\" \"Gender\"   \"Age\"      \"Height\"   \"Weight\"   \"BMI\"     \n",
      " [7] \"EA\"       \"es\"       \"RHR\"      \"RBC\"      \"Hb\"       \"HCT\"     \n",
      "[13] \"Smoking\" \n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Warning message in geom_density_ridges_gradient(scale = 3, rel_min_height = 0.01, :\n",
      "\"\u001b[1m\u001b[22mIgnoring unknown parameters: `size`\"\n",
      "Picking joint bandwidth of 0.386\n",
      "\n",
      "Picking joint bandwidth of 0.386\n",
      "\n",
      "Picking joint bandwidth of 0.386\n",
      "\n"
     ]
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAA0gAAANICAMAAADKOT/pAAAAflBMVEUAAAABg4cIvMIJvcMX\nv8UZwcczMzNIyc5NTU1O0NRoaGh8fHyMjIyampqgKCWnp6eysrK9vb3Hx8fIw0PKxkXQ0NDZ\n2dnh4eHlPjrmPjrmSUbnRzfnRzjnS0fnb2zp6enrZjzr6+vtaD7tdXLw8PD5zkz9xRz/xx7/\n1FL///+5TF/+AAAACXBIWXMAABJ0AAASdAHeZh94AAAgAElEQVR4nO2diZbcNpKuoRl5RFWV\nrWWmJEt3VGq71NPN93/Bm9yxBIAAiSXI/P9zrFwjwczC5yCBWFQPQdBhqdYHAEFXEECCoAwC\nSBCUQQAJgjIIIEFQBgEkCMoggARBGQSQICiDBIL0XxA0q/Vc5EsiSKkGfyUPkWxRYQiZFn/1\natD78d/qBwWQjgggCbK4MbSJhRJAkiKAJMZCqXfvDTFQAkhSBJCEWAzeyALphlLNgwJIRwSQ\nZFiMJ3UOSFGnBJCkCCBJsJgvjlyQYk4JIEkRQGpvsa4xUCCFSQJIUgSQWltoS3UkSEGSAJIU\nAaS2FsaKNw1S6EIJIEkRQGpqoQxiPCAFnBJAkiKA1NBCmRz5QXrvi3QASFIEkNpZKBsXP0gT\nS+78AUhSBJBaWdjuKAYS6ZgAkhQBpFYWLkdxkByWAJIUAaRGFgRHLJDeG6t4AEmKAFITC+K8\njg+ShhJAkiKA1MKCxCgBpBUlgCRFAKmchZrlvuChIwGkGSWAJEUAqYzFANC7dcobPNGndckg\njdu0AEmKAFIJC0VlRUws+TFKBulGEkCSIoBUwEL5uFAhjNJBeq8AkhQBpOwW3qyIN2/e/BYk\nKRkkXmEH5tcASEcEkHJbqJUaW7+NynhqN1ikogSQ0tTNGu7OzxhPLgJImS2UWql5+xupbIsN\ns0UaSgApTd1229n3eo0kgJTPYlqc24jxgOR3SvtA8seGp30NgEQJIFW1mAo73qa0zosXJJ9T\n2gvSe09seNrXAEiUAFIti4Wh9zZHAZA8TukASAtMlJhfHCBRYoA0FXz+Czqmd5vU203zJH7r\nk1Lvaon5RQASJX2xYb2LxYaSFvr52nip9Da0sEClj7f9GgCJUrf+Y3ukzngfQMpk4WA0n9oF\nSHKmA0BiqvqpnU5OZ4E1CSDlsXAxWq6RAvtG/OuXfQeVZgGQKAGkmhaGO7IXG4JRQcXyXdMt\nABKljR4HpB7XSJmziyh3pK3aBUnS3RJAYkrWqt0ogHTUwoeRtvwdJmlzSwCJKcTaSRkil4Ue\nzq1MjPR9pBhJM0oAiSmAJGWIPBZ+Z2RvyPJIAkhMASQpQ2SwUBGMzMiGKEkDSgCJKYAkZYij\nFlaGHoWRFSIUJylvml66BUA6IoC0w8JOdKU5smLtOCRlTNNLtwBIYXXBVwFSqoWbLu7hKB2k\nnGl66RYAKaguTBJAcuUPm1YuRX6O7OjvOEk50/TSLQBSUAApwUIpZS1omyLPx3wcOWkUUZJy\npumlWwCkoBaQhqDvJRZcexkgjQqAYs7yBI7cfKQYSUYhvDpfXBNACqnT/zMDwJGPNGms5bhX\n/oQjKgcp6ZNnVfsdAFJIOkg9kUkBj3TEItWHRSYAlr+Zqg/SGu+9gmRl9gGkAxaRUzXiZDB8\nxgaQmGoA0pocOz5yF8MB0n4L7iUP2ykBJKYkeCTrDQBptwVzES6BJIDEVHWQtrwJYrFhFEDa\naRG+PAqAFCAJIDHVECQsf2e1YGDkr67lnQYAianWsXbE1ixA2mUR2XMKg+RdcgBITDUEiSgg\nNAogpVoshYmtPVwCrUC9R3omACSmWnok65RuEUBKsRjJWdpKzNEKai35bcdGhAqnklMBIDHV\n+tSOEEBiW4yYvDExcqSjFKxATJ3eASSmAJKUIXZYDIREKLIC6sKlvAHSfgEkKUOkWygVc0YO\nSZGa+Ki0ulvNQHIrci0CSDwpJkU6SdHmEjZKAIkpgCRliDSL29XRm2CTFpokRpcWEyWAxBRA\nkjIE00JbkksBaV5yYLU70jOPABJTIkBCZAPDwtgk0npLJDklbt+wNY8PIDElAaStGjgS+7xS\ndnZdUv5eehLfbaDWXxmJfRx1TjrFInikgEaX9GY+WUvtS7mj3iM8ElMSPJL2cBBA8ms8s3uj\nn6ylkXSyLw6Q4gJIOyw0f7QLpFhieaWvwbYASHEBpHQL0x/99ttbVuqErnepf2+AxJQEkLTW\nY4MAkkc2R2Nr5USQUgunAiSmJICE5W+OhXI4Gpe/00h6l3p2B5CYQqydlCEiFhMwZlBQpEc5\nDVIaSQCJKYAkZYiwxYwLAVISSeOCecrZHUBiCiBJGSJoMfsjK0qV06OcACnFKQEkpgCSlCFC\nFtR53W/cHuUESHynBJCYAkhShghYKMod/ZbQo9wBiY0SQGIKIEkZwm/hTSdP6FHugMRECSAx\nVRGkLbpuK1u8PK+/DyCZ8ufBpvQod0FitT0CSEzVBGm73TaRpu3YHvtIPgul/HmwRo9yFkpO\nmGus7RFAYqo9SOaLPUCateQfcduG7QNpgckHFEBiqjVIKBDpWhhlHgMcpbdWjpXjotvUVvvi\njgASJQckK8auR2LfpL3t9/Y3+TPU+utrAkiUyMUGeKSgRdjL2P4l/sc8zRefBJAoaasKd31q\n57sgISxS++9FV+EAUilVP7XTF+nuEKStfEncIroQRzWyzPw9ABJTrUHq72rVTkfD8R7Oql0E\nI3rpIPwHBUilVH+xwaLnnvaRLDSCC2S71+DybgsBJKYardrdZWSDy4aBkmbBahrm7QibsyUs\nQGIKsXbVhiDZUIQFuxJDciNLgFRMAKnSED46Nv/x1/LGHbHc3g89+j0AElMAqc4QATiUZpFA\nUQgkr08CSKUEkKoMEcRj9h9/pVEUBMnnkwBSKQGkCkNEAVGcNyWB5EEJIJVSVZCMPSMzWkhb\nuLscSAxCBmeUWsmb0X/veAM+gMRUK5A6e2N209VAYnD05o3it1xhg/TeTTcCSKXUDCT9mUuD\nFOVoSoBN7y3BRU+P7QNIpdQIpI56ftalQApf+bx5o6WRZ75GInFiJJdn+uJZLAASrShIl8tH\nCqQIDQxZ+USZEorCGmBq/bNwBZBoWc3FtueNRxfySKnlhOW5C3gkpmR5pFF3DJK8CvcAiSmA\nVG6IxJ2h5LrcYr94NguAROu+Vu18GBntyW2QkpyS0C+ezwIg0bqnfSTaHQ0ErYXorLck1+WW\n+cUBUnlRkQ3a87MuARK5K6Ts2loGS++2t5U6KoBUTIi1K2FABvw4GFkVUjUL5l9F3hfPbAGQ\njuj0II1sOKWyvJUelQsS0ylJ++LZLQDSEZ0bpOVszS5XHyiYqlyQeCiJ+uIlLADSEZ0YJG0B\n4R0Xo/X0rkK5R4BUTAApk4G9pP2OjdHilCqUewRIxQSQMhhQ20LbYnYcIw9IUZSaf/HSFgAp\nJLfwtxnqcDKQPAniY8DPJCZJnpYrOb8GQCqmFiCtN92yo3RSkOgIhQWkG0Fv3vznTSyUvBmy\nAZQAkhwBpD0GvigfHaQbPRNHA0ockgLFtTx/JYAkR21B6qcTvDOApHSFCFom/4YR0ymFPpXO\nyQNIctQMpBUhHSSZiX3TLE7Lnnv79s1/GGJ0DIsOcZqEvFwCSCHpiw3n8UhJUu/dRuRRN/Yu\nNa9P4BfPbAGQQjKykrr1dtX5QbpxZPV35ZCEDFlHACmky4OkBnfkghQjCRmyjgBSSFcHSY1n\ndftASiNJ2BfPbwGQQjITzrv+YiBNHO0FKYkkWV+8gAVACsmMbLgaSMs6NwFShKQl1Zz/JxH1\nxUtYAKQjui5IYZK2DNliXwMgFRNAymqwbbySIAVJQqq5I4B0RCcGSQtgoEEKkaSnmvP+LHK+\neCELgHREpwXJCPQ+BBITJSlfvJgFQDqik4Kk1Hs9oM4DUoAkK2iVUe9exhcvaAGQjuiUIA2B\nrEZgqg8kP0lU3SEk9p1F2UHS+u9pS9qd7+2ETgjSGA9uBnh7QfKS5EnsC/yF2n/xwhZ3DZJx\nYz3rfazrdCBNaRVWokQmkIIotf7ixS0AUrhM/oVAWrOT7IQjP0g+kvxtw3wNwgCSHJUEaem1\nPD5aTvem9kjav0bx4kFnAclI8XMS9wIgeUiKt1a2aQJIclQYpOVaqdMjgbQoO/25Xmpin0dW\nIl+Kdrfma/2dKwsgGfFznQuNA5Kms3gkTYSLeRdKSid/9bb/8283BDwSKYeerdVlt6zpbWd9\n3dbiZdX5QHJw2YpweVBqdMUDkIqp+DVS73qkXvNI88MzXiOtslkZIVqvkTyNkjIcVPMvXtwC\nIDnXSPpt74B07jQKk5TZF72NrC24PzxAcgSQdE/U8RcbRp0NJIsjYtWOIgkgMSzuGiQzsmG4\n2znL3/0Vlr9nkf7IWv4mSAJIDIt7Bum4zgUS7Y/sfSQOSQDJEUA6olOBZBASSKNgkASQHAGk\nIzoRSOaKXDD6O04SQHIEkI7oPCD5TusokOIkASRHAOmIzgKSCnHEq7SqYmNk/hoAqZiKgtRZ\n63HWq57nzwGSvc8aj/4mF8FVaIzsXwMgFVNJkDrtX+/Lrk4AkhNE57Zt4RaI3FACSI4A0iA6\nM8l93ZZokOhQVKL7Eb/S6oISQHIEkAbpoBBpSb2VrrS+VwxIihCNggtNUqXVKdEIIDkCSIPs\nkg1WpJAZFD69T04+UkprMX4ykvcjb6O1/sYSBZAGUVkUodtFYjwS18Db1ZzwPTkPqvkXL24B\nkAbpceCdByj9+UUnA4k63fOfCbatCQSQiqkSSPpTnqyKVecCiVzUXq6RkkgCSI4A0qB7AIl2\nR9piA7HC5/vJAZIjgDRq20ciSzac/xqJXMRT1qod4ZToHx0gOQJIk7bIBq2zWK+lKRnPLzoL\nSJ4ccmf5mzq/Q80GlgVAOqJTgOQvEETsI5Hnfy2+BkAqJoC0w8BLkbY3a2bI0it71b8GQCom\ngJRqEKDInyHri7NT9BilvgZAKiaAlGQQpMiIFWIk9lmneADJEUA6IrEgRSh6H2405r2oUvoY\nZb8GQComgMQ0iFIUbzQWjlkFSK4AkqbOuPHfXSUSpDhG8UZjoWurOl8DIBVTC5DcF41X5YHE\n8EasRmMhkpQCSI4AkqaTgzSFnkZ6FxEpsmR/pCCQjO7L+7/GXguAxFRVkLQ4BrMCq1HbQQpI\nevx2DCQ3tc/TaCxA0rslarz1F688BEDiaQNJi6wja4JLSuy7KaEbWEKfMcantv7icgSQNHUd\nkY0UyuyT4pHYBuQJm9eHIfqbbwGQNGkeaQPqSiDRFz6Bk0HPbw6QHAEkTdapXX8xkHzrB6Gr\nKqRRMC0AkqYrg2Ssi5v55cHlCaRR8CwAkqbwYoP+0qyzgGTuLmnr35wFc7S+5FgAJE2R5e9+\nuXxaDU4Bkr1Ha61/KxVdMG/xNQBSMbWMtaP3aM8AUrxicXjv9T11dgeQHAGkmNacc0LiQXIr\nfxM7r2/jKNX/GgCpmFp5pECfCuEgsSp/T5ENEZQspwSQHAGkI5IMElnzkYwFehsJCHJRAkiO\nANIRiQWJDAInLo82kKKnd/r5HUByBJCOSCZInlQKD0Zb0CrfKQEkR3cOEqdPn/8NAkHyNnTx\nuaPfggUinQ9Rdb7GHguAxFQBkEIrckGCZskBaQtV8PSW8GJkFIiMkTS7JYDk6K5Biricc4Bk\n95KgQAq4IwOk+IXSey2+qPEXbzAEQKLVafeWrL3xkVG1eEvq2+oXz2oLEt2OxQXJxGjlgAKJ\n5ZSWMbTugHW/eLMhABKt7Qqp69Z/rPr5c1iQ9sxkIiCxj5nJZ6TyKfUfizwpfglJgkjw23TX\nIA2ySuZbIBFoyfFILINAnN3ykuXDGL8zrpEc3T1IvUWIgQ2ZQnEmkOx4VfNayVPlQcSJGkAq\npvogdef2SPFAO08+UvSaByA5umuQ3Pwj3zWS87ZJkkFyliGopTtFghR1SgDJ0X2DtIKRAFJ3\nBpCI1Tx6BVwBpDwWdw3Stm5n/kMsf2+vnMAjkYF2nk0kzxZu+OwOIDm6c5D2SDxIgXaxJEme\nWIi2XwMgFZMAkM5wjRRqu0yT5Ek1DzglgOQIICXJCnKVBxJZgSEcIeQPZkCBSL4FQDoiYSB5\nglbDGP3221t/WBAKRHItANIRiQLJV6UuxtFQs8FPEvmrAyRHAGlUR90Y9/S7q+SAtK13O3EK\nMY6GoNVwO6R6X+OIBUBiqjxI3XrrfYv5ohCQQmkUcY6m4id+kgiUAJIjgDRp2zPy5SGJA2lL\nYjCm/T6QIukTVrIEQHIEkCbZIEluNEbh4wOJwRGvitCGU3pWX64v3nwIgBRVZ/5nZ1JYOUl9\nu3yk2xxOyBPK21bM+OShlSy0CiBNCoPk3M4Sco3kNWCluy4+LOH3xamdI4A0y8ziu0ajMR5H\n68kg/3wNIDkCSLO2Fbs1XrU/OUhMjrSrKu5PDJAcAaRZ1wOJy5G+PMH8jQGSI4C0yFjephYb\ntqdWSQaJzZGxzsc7vQNIjgDSInOf6OyNxjgF6iiQeE4JIDkCSCzRe7RyQSIaUSjPBq67hYvi\nJzssAFJMgWAHsSC55RqIGpE+kFD8ZI8FQIrqdI3GGN0uZ5w8IKFmQ7oFQDoikSCZHKlQVp/y\nVRFCzYZUC4B0RAJBCpeEJFHy1GxAqnmKBUA6ImkgDWdr7xIwmlDy1GwIsASQHAGkIxIFknJO\n1Dih37+l5iKV/hq7LQASUwDJK30V7t3GAI+j396GN52QIcuxAEhH1B4kd2doieXmYhRLNZ/c\nkvnjAyRHAImlzmxBtqg2SMqRO+vfJWI0p5rHOzFrGX0AyRFA4sgOXO0bJfYVyOdLzuur/JXP\nIoDEERWwOqj9qR1lkBJnt/qwhGyk1v/zbzcEPNJBLXl+vRXjIBSkNI6Q2JfDAiBxpJe3k55G\nsfqjcI0UAiQk9h2wAEgcdZ4HAkEat1dHgv5nFIMlfeeJ9yMDJEcAiSNisWGUOJDGyIaFoVUR\nlIzIBhZKAMkRQGJJyPJ3TGp0Rv/jKkgS8pEyWACkI5IF0s3x3Cj6b4KjsFNy85Gafo29FgCJ\nKYAU1nxdRIMUckpEIxjkI6VaAKQjEgTSekrnA8lPEtmarNHXOGABkJgCSH5pV0ZekLynd2Qa\nRRAlgOQIIB2RFJD0FQY/SD6nhB6yGSwA0hHJAMlcqAuBRJMUSOyr+TWOWgAkploWP1mXvcWF\nCKlpra4ISF6UAJIjgBRVZ9w3SGoM0hy1YG4cBUEiSQqA5EmRBUiOAFJUEkHSwujsDdgwSBRJ\nQZBIlgCSI4AUlSCQiHw+J44hAhJBUgyk93PwXravUcYCIDElACStUYWQxD7138lKbM2HlD6W\nAFJU2mKD3vFlUOvFBqX+vWl2Vv/8d0ynOFGDRyqm9h7JWbhrvdhgUPSvSQZcLJJEYgGQikkA\nSNo6+Ki2IOkc/WvV//0rlSSRWACkYhIAkvW4KUiK5ugGEsMpKdYQNb5GPguAxFRzkDr7iZYg\nGVdH/zJBYqAkfg0OIBVT88UGSSD5/NEM0r/i53cqNkSNr5HTAiAxhVi7TcYyw78okBhOKfdB\nNbYASEwBpEV+d6SBFEdJBYao8TUyWwAkpgDSJOW9PLJAiqG0XCeJxAIgFRNAGmSy4XJkgBS7\nVFKZDkqEBUBiCiDZGFEcWSDFSFIZDkqIBUBiqhlInbMRu6gySPaZGsWRDVJs+e6GkkgsAFIx\ntQPJ+0pVkJwLHpIjB6T4mkNK+fzjX6OYBUBi6p5BGqJRHQBIjlyQok7pn8ksASRHACkuo4R+\n9UqrioLIzxEFUoSkf85+if8DAyRHACkuK9iuaqMxpf5JS/1firwfY36mKv59LiuAFNe22CCo\niL7XyXjykQK/nkj/Ao9UTBI8kpg0Cv/Jmi+x72RV6gBSMUkAyXpFQqwdF6R/n6tKHUAqJoC0\nKrR4EEg19/yCIrEASMUkBaT2p3bBRbhQzQbaKYnEAiAVk4DFBhmNxjwcKU1JJInEAiAVE2Lt\nRtGbSlvxkzlD1scSgZJILABSMQGk3osRsSHrZekcdVMBUjEBJPqsTpGp5qEoOwslkVgApGK6\ne5BIH2NnmpshQiyURGIBkIrp3kEimQhnyAbC7LTQOpFYAKRiumuQPIGr0QzZUBYFUs0zWgAk\nWp1RfMtY9a6+j+Rdz2Yl9oVivxUyZHNZACRaBkjmPmxFkIKbQpQ7IkEKpvbdPl8kFgCpmCqD\ntBUo7tanjNu+JEjrxqo/dI7EiM5HCickpafIAiRHAIkWAdL4SCu42pcAyQlN8AZzeziiQQo6\npX/OUREZv0YLC4DEVG2Qtv/WK6Tp0Xi3UGIfJ/9uysFLSuwbcvuin5n9y9yTABItu63Y1mhM\nQNDqzjSK0gfV2AIeiammIPXEqoOIksV8kLwkicQCIBVTdZCs1stiQGKUMvGQRP+EIrEASMXU\nDKTtAkkCSLEydcEesshHKmUBkGjpzfm6lR9tsWGUkOhvgFRpCICULLPL5bpuV3z5O2zBaLQc\nBokkSSQWAKmY7jrWbhAHo7luaiAqKPNBybEASEzdO0iBOG5T0was9+1ZD0qQBUBi6q5B8oCh\npZg7kQ3IkK1pAZCOqBZIXorCIUJelLIclDQLgMTUvYLkdUaMWDtf/oUyh6jxNYpbACSm7hIk\nfwkTZtAq4/xOJBYAqZjqgrQlTRjpE2at1fL5SJ7VbJ87IkCK55qLxAIgFVNlkNbNWCNV1iSp\nIEhLMgUFUgAjqmOfh6R5ua/1DMxmAZCYagWSvjlbAyQzIYkAKYRRWqr5htOifF+jugVAYqr2\nqd3qgeqBRGSWOyAF3REJUqyLrD4EjyeA5AggeaSBtOVTaIkVRRL7OBl9bjO+UTk69iHHb78A\nkkcxkEbVr7TqdDZXf09aXRk69jWxAEgeddp5nZnl1zJo1YfRzFIAJH+fMZlYAKRiagfSmpjU\nuPWlw9HflnzLfGGnJBILgFRMAkDqt39H1Q1atTga3JEyfdLf3o2nkFMSiQVAKqb6G7LW6Zxb\n2K5l9PdAkPrf//1fyy0pJPY1sQBIHokDycORS1K4GGTeg5JkAZCYustYuy2NwiZi4cgm6R9/\nR8qq5jsoWRYAial7BslhQ+PIIukff4dJcp2SSCwAUjHdL0ju2ZrBkQNS7PQO+Uj5LQDSEVXK\nR3JR+NsAySDpH5wrJeQj5bYASEdUASSy3aXFEQFS9PwO+UgAqZa2jkjGLqym4iApcjWbBVLE\nKf0brS8BUh11Zn1ICqXCIHn6I43YxEGKo7TroMRaACSmmoHU6zeGCjcaG2a7C9JEjQGSTpIG\nUvz8Dq0vc1kAJK86ouWldZJXAKRoozGKIy9IMaeU3GKM+zUaWAAkpiqD5DR2MYvol2k0Fs8b\nUv8Ypf6fqflpV6xEpKGRLHRIAMknCiTjtm9SRP91lPphaX7+ppdXU/GfTaR/gUcqphZVhDob\npKZpFCtHLkgbSTZIr+dMHAdIxVS7+Mmce2ReI/VtPZLPIYVAijolkVgApGJq5JH0VbvWjcb8\nDikIUsQpicQCIBVTg/5I07ndto/UuNFYgKONJAqksFMSiQVAKqZWIOkXRk0bja1OZwdIIZJE\nYgGQiuk+Y+02izBHK0kekAKndyKxAEjFBJAOgeRHSSQWAKmY7hwkmqMpDkInyQ+SDyWRWACk\nYrprkNS246p0jL6NUkyQaJJEYgGQiumeQVIaCxpH3xYpJkgkSiKxAEjFdL8gae5IB2njSCcp\nAhKBkkgsAFIxFQcpnshnqw5IysCA5GgiiQfSgBJSzXNbAKRVa/6RP5HPVpVUcw9HFkgrSQyQ\nJpaQIQuQioiRyGerfOtLZXLh5ygRpAUmJPZlsgBIq0KJfPbtrMIZsoMzejFmvp+jlSQ+SBtN\nqal9AMkRQFoUSuSzb/tSiX2rXhzdZvt3TepPR7fXlWvHU7Evci8CSItCiXxETt+oWsvfyrpS\nevUGgCuZ3gIeSZDKghRO5OuMy6dVpUDSWiMrAiKao5EkgNTIAiDNiiXydYa3mlUGpA0cZ7Eh\nDNJIkshJDpAEqZJH8ibydZVAMv2PJ71oDrMDSFWHAEhRhRP5iMWGUSVAss7jvCCpLcjOOrkr\ncFBnsABITNUCiUrkq7f8bV8PkSCpdflbAaSKQwCkQsoPkrOukAbSjaSXa5R7BEjFBJBcjgiX\n9JLsk0RiAZCK6R5Ache6qepaTgKFThJAamIBkI4oN0jEhhEJkpNAAZBaHxRAOqK8IFEbrwRI\nishEOrTeIBILgFRMVweJwogGyc1EMkFKJEkkFgCpmBqBpK14Owl/OUGiOSJKeVOJSJq+jySl\n/FgisQBIxdQEpG7bgyUS/vKBRJ7WUSA5HNkkfZ8+KeHXEokFQCqmNiBtN0TCXyaQyLBUGiSC\nIxukuQgKP8lIJBYAqZhagNQRd3OHCAUoskEawuscjjwg8U/wRGIBkIpJFkj5EvtYiXdLYoWb\nzjdl9Bk5f8jXqy+AFFQNjxS1mDOSnFhvY6FOd2FY/q5vAZCCEgDScubn5wgg1RoCIO1Vc5DW\nCyg/RhZJL2lLdnsOSqbFGUDyXrWaL6T3mU/RdVftvFJqWWwIcgSQKg0BkHar1j4Sqa0cV5gj\nB6Q0kkRicWcg1dTFIxscqa0CcYQjF6QkkkRiAZCKScIxWCoI0nJx9OLnaFt+cEFCZENli+hU\n+NCpDzNInx5U92l99vFnPxP2/KjU4/PyaHjbw/g2pX4+qe5j8tF6dFcg6U3KPRWD1LYVC5Dq\nDHEApMdhE+NpJORp3BF8XJ/tfk3ofJq2Cj/NID2ub7u9Zbibi6Q7AkkLdnjxcWQENSgHpASS\nRGJxMZA+q+5r/7UbCHlWj7/6X4/qeXj2dvf3m6ca0enU1+Gph+nRYvF5eHh726fhhSy6G5CU\n6WBCIC0kESDxSRKJxcVAelJf+oEhNdy9eaD+l3qan/2lugkdNbA1anrb82jxODz80me8vroX\nkKy6dkGOzK6XJkhskkRicTGQZgomXtY6uhsbw70Pt3O/r1+3t/Xm3QuAtNQtXh6uL5Qox2WF\nsPoWGqyIVUWAhKDVihYZQOo/DpdC3c/LgmSUh+zLguREgkcckuuSzHDxLAd1DovzgGQ/u917\n/vCwXCNdD6QtosGppJ8ZJCIvSX2PcOS4JKszGeNXE4nFxUCarni+bBc/ox6Na6RJCznLNdLT\n1UDqC4PkaToRBcl2SXYmYDzBTyQWF8ApVeoAACAASURBVAPpeVu1G5fj+k8DIZ+G5bgPy6rd\nw7BCR6/aDR9xfpC00IZ+5ShzozFFtgizEo3oJmPKTkJyPybbYUI+xf6fOm4e/a5tEA3XQuY+\n0ufp0ukLsY/U9xcAaVC3xdxVDVr1Vlo1/JNxOSTSW9y9RxpXErTIBvX7z/HZYaXOjGzYVro/\ndWtkw/ZvBjVe/nY6+vWtQCIq2QGk1geFfCSuZpdkRK2Wjv52L3kIjmaSAFL5IS4K0qfbZdnP\nB/Xwpey4eh5SVZC26G8OSAtJIic5QBIkG6TnKT5pujwrKC0lye7ZVxKkeRGPKBBJrOIBpNYH\ndWKQHtXn/qt6GCL/Co9srdttKplGQa9mB0CaSRI5yQGSINkgDQ7p67IG30Z10iiiHAGkSkNc\nF6Rx+/eCIHkifgLdzFeSRE5ygCRI7qnd1+chuqL8qZ1XhUBSZDC3n6M1rEGxh0g/KPEWAIkp\nYrFhzBrc0jiqq1A+ko6OVbKYBkl3SSInOUASJHf5e9gr7vuHzw0OZlKNfKS4PzJdkshJDpAE\n6T4S++zQ1S3hNVBqVSdJ5CQHSIJUDiRrj6gb17unNe/1jnF3UaWu5mP0YoAiDaRXJXKSAyRB\nckF6HquyPP08+skuSNRLFSqtEpkUL6Gi3yRJqcckE4uLgaQCSj6Kg3IGfJzzdbujJJm7rV3v\ngkQnyNZoxszDSM9HSv7LiMTiaiC996o5SENW1FQO7PeDn9weJKU8XfvoDNkQSS+cXD7WQZ3M\nAiAxZQ/YqV/TXuxh52g0mjBTJbwg5U3s86bk0Zl9ZLafYZjrwCCmTgzSWhaiAEjbYsP2SvFT\nO0JqdjCUs3Kc174hLmMBj8SUPeDD7JG+Hi5BuccjjaqR2KeMKyCA1HKIa4I0XyM9d+rTwU/W\nuensJ9bbNiC5pVTJFYnBayFotaHFiUGai5Gr46F2UkFS2mJDiKSljhCCVttZnBmkcR9JPR2P\nEHIaXLbaRzKlXnkgbZX0EWvXzOLUIOWSHr6gP9EgskHTyNFW185L0rbRpBBr18wiG0iBPdrb\n8ywIIm+yX376wPnQopIAkr5hqxBr18oiF0hK+9f+DO5RJoIkoI1g0ZoNEyTff4RJMgMf1OuO\nkBORWNwpSMq6pV6LKhGkh7HPTFOVrtkQB8mtcTdtPKXgJBKL+wTJ8k5zZcheLV0sxjeo6Rxv\neVJ/63QnEaRfT4+FC3FFlQkkN3px3oJNB+mHWjv2sVkSiQVAmqFZog7sx/or63/b66FjsR+3\ni59dlAWkLW5h+9/LhkkYJCKiVXsb85cRiQVAWq+WlHZrEGO8Yt4JHov9+BIgWfE/RvTqgMl3\nEhE/Rz++W5+356BOaQGQdoLEE1nYcc8nUDoMUjiKLgYSmWHx/UcqSSKxAEgpIK0tAJ1PoY4l\n/LJHPJB2cnYQpEgwqvphguSQxAGJgZJILABSskfq7xOkeEy3A5KFCJ3y54AUvVYSicV9gqQv\nfwu7RlpB6tZbLVKh3yo0mE8Yb3BfmrUbJE5mhPoRBsmTOvudXJYI/UgisbhTkHQUbHD8INVY\ntXNBmuFYIoI2WKwn1sfEe48m9gXa6wWT+lTkdTLJD7l+FVQiRGjdR+pjIB3aR5r15fEpZGXm\n6Jl8GLf0C573ziod2fDqliy2X3f0Yr4t70FJtriGR6og34C/gjUbtmskxxNpObBbWqzxhG4q\nA6QVEe+pIUBqYnEBkMLnhEYehON4ep0b+wnyLK8WSP62LtPLYZCSSBKJBUAqJt+An1Roze0Q\nSM41kv5S3wYkc892ecIGKYUkkVgApGLyLzZ8DFi5IPm8jO/iqQlI3v5IBFbjep5jwP/7iMQC\nIBWTD6SHYMkGfR9p/sdd3e7N5e/eWvN2X5pVrz/S/F1djJylcYDUxOLEIKXL5uCwaoG08mKG\n4plVWO3VCfbvJRKLq4EUUPJRHNT9gGRf8lhbr8sfwN6Ktbs3c38wkVhcDCRJck/t5jsdj41t\nNTubsoK0/N/JPIHjFtFfSdIuqpgkicTiYiBJ9kjLEfw8dRrFpPWMzbkOemFjNJNkdCY7dFAn\ns5ANkn11m/y/u3zSB3w2kD5aaXW3smXIBn7mBI4ckHh/JJFYAKRiMgZ80DnKn3Fu7CkZa3a9\nfnKYOUOW+pXtbhTEtZFJktW9eedBndACIDHlvUYqoOV6aosUsrdwR+UAKcyRGf19w+jbt28h\nlJQ/OC/loM5oAZCYqjmgAdL81OqftrdlyJCNpciaaRTfJoW6MjvBedHfTSQWAKmYvAN+CYZ/\n79ISTdQZ3OQFidpgPQzSVkVIRyn8txKJBUAqJmfAD+UWEGmQes1BHW40RuYMhVOS1J+LUnOR\nVLa8G4jWiUHaOHrOPlYcpFHlu1EY20LmqkK2v4tI/wKPVEz2gJ363D+qnz8fVZFVu4WidiBZ\n+6t2cWKPXpL/MCKxuE+QqDMs5t+T/2enVu0+3rzR1+MNkhx5QOo782HxIvoASdQQ5UEybgIf\nx3qKaTyA9Dx06ytyjbSd15nx49VAcjJkuSAlnyuIxOKuQYpSkRWkp9up3U/10H8pA9L2nx7r\nakbq1Uzsc8vlA6TaQ9QFSem1T4yCKGtUJr/iCTHIoufhYx6HzwzVbNgnHaQ1sqHv64HkJvYB\npPZDVAWJ+m+5o9/n1eAiBln1cXjmd6XaNRyrCJK7deT527wkrwOJxOKuQVoRmaHR75Nv6Ak8\n/MfCfmc1lQJJ26n1g+Qh6eU1lSSRWNwpSNuqHUAKiZnYZ3FBc+QhCeW4mlhk9EgzGAtTyry/\nvs968ghIQ1fzvn/6yf6I3MoDkrV5YCf2eTmiSQJITSxyntppOPWGIyI8Up8BpMcZyK4ZSVmj\nv5c4DYoLmiO9eJBN3rGDOqPFJUGqcWr3ST3+GkD6VGDVjqnjIEXjVsMgjflJFEioa1fZIv+G\nbLVVu0790jppFtSy+u1uJR0FidGT4uWVKNpgZveZLG09ZHce1FktLgRSbB/J+Lc/uo807Uz1\npUHaIHKLpxwDiYHRuC3kUuRkUhDLfKgiVNWiXNBq9tltf+DD7JG+lq3ZYOX15QoRiiUjbZn0\nNkdLTpIHJT1cnPc3EIkFQFpNk48y8QPna6TnTgVLrR6UldeXJ7KBQdECiFWzQS0cuel9VPsK\nVq6WSCwA0myY/3TL+cSn+X/Z+YO/NZkgaeUajiT2RdL5vGl7akvtI9L7FPqLtdOJ85GmfST1\n9LnoqAZIXY1YO/M3N87U7LM86m8i0lvAI4kGqYZ0kJxzuxIg0avZr7wgIdV6PjW0AEhMtQfJ\nelwEJPsX31azXY5IkkROcoAUUPJRHJQZ3Fdt2EA1rgIgOWS8BDAiSRI5ye8eJElyQaqCk72P\nVLY/EglSoCKke8qQ/puIxOJiIMn2SJWOwYpsyF2yWBcVOhfuRuGSl/yjiMTiaiD926v7Acmv\n3CARl6TRbhTuRVXqryISC4BUTNcHieCI0RzJWeYDSA0sANIR5QWJ4siObOCAhFTzBhYA6Yjy\nduyjOGKA9MPdwU37YURiAZCKyQSp6brHopwgUVt2PJBMkpDY18QCIEXULVru6y/mA4mMYh2u\nj5ygVTcenAIJiX2VLU4KUl0ZG0hFNmTJCJIRGKvRGJVBYZKExL4mFgCJIZOg/BuydFLFRAvZ\nH8mTQWGAxEdJJBZ3CVLKKdZ+HKSApKlkD9mZle8URyGSjK7myEeqZZHNI3n+YIrxHqZkgXS4\n0dgsOonI6TFm9hkjcpH8yU3HjxGKCyAxpIFkLjfUrP1tp1FYfmz9dUR6C3ikZJDW0ifKLJu/\nPDDqcCUtuIkAqS8ctDqLrGUSWqvbSBI5yQFSKkhrES67ANfyQAdJ9Sl43BFI5CVPeNV7JUnk\nJAdIiSAZjJisaA9soHi6H5DIRbh4gqxKGCL9oMRbXB+k8a46PUhVEvsGUfurdLVViiSRkxwg\npYK0LIMbIC3PrO5JLVdIKWEJzUEqGdmgiS5+QkeBEySJnOQAaZdH6k2Q3GsilXh5ZH62HFUs\nfsLrR6Faz6eGFhcEKXaNZIB0Ao/kVb3iJ/5+FDZJIic5QEoEybgMMtmxqdLfyBJAYoCE4ieN\nLMrtI03/mBtIa9F8ZbyZp7sAyVdFyMcRQVLy7yQSi7sFqbzuASRP37CU8idINW9iAZCOqEbx\nExMkooYDQKo2BEBK1pbOp+X1La+t7ypf/GTKHN8wGpKRbJic9fLEszuRWACkYqoLkn2vKw4S\nnU6hgbS1dLFgcndwk1ASiQVAKqa2IJE1izOC5OuY9LJx9E2XThKZas7/uURiAZCK6bogDQ6G\nxkhvfWmCZKBEB+dx10RFYnE1kISWLC4uEiS9AniuxL6bvEl5Roaf2WPMTO7zp/VlOUAorpMW\n0S8ubbFheaY3QBpVLrFv1eKrgl1d9J9GpLe4e48kSbI80qjyICle0Kr224ic5ABJkASAZPe+\nLAvSeOkUCRFSAKniEAApWU1Bmi9CtbWDaIOk7ccROckBkiA130cynx9UJI1CEavZ8Vi79dcR\nOckBkiA1j2wYnzfeVSBolYz+DsXaAaR6QwCkQsoftEpHf3OCVpefR+QkB0iCdH2QqG3ZlxhH\nNkkiJzlAEqSLg+SJbniJcmStgYuc5ABJkC4LkrZGtwskkySRkxwgCdL1QFJBhBaQ4l1kN5JQ\n/KSVBUA6oiMgxQjaA9IUqZoaDykSC4BUTMVAsraIut6Os/NuJe0HiUfRAJKdxRdr2ae3dXlF\nW5daFgCJAsm8s90a7+v3g8TGyO1BQXVH8oPEyksSiQVAKqbSIG24WEmx3XJjvr3fCRLznI4E\naclJCpD04nxCzC2JxAIgFZMEkIYTviMgRdcWHAro1pcBkhyQojCJxAIgFVNxkOxMic58Znk4\nvbovsS+Ywhfs2zdeG3kb9vlT+zaVSGeDFgEkCiSjcJAFUpVGY4uMNIo/vHUaXhFr1/qgAJLf\nI81PdcZNVZDUWhRo4Mg4o3POEBFrV34IgBSUnjJho2Ku3FUGSSk91u4P49rIvdRCrF1LC4Ak\nFyQ1rx3M8JggeV2SyEkOkASpAkhuwS07QXZdbBhVohvFpnkRTueI4ZJETnKAJEjlQNpS9yIg\nHV7+jv3pqHwkpXMUckkIWm1oAZCOqEY+kumQgi4JrS/bWQCkI8oLErlVa3MUdElofdnMAiAd\nUd4i+iRH3y2Owi4JrS9bWQCkIypfRD8EEk1S+s8kEguAVEyXBskTgad+fLc5irik20VVtoM6\nlwVAYkoKSAVW7XyRrDdkvjscRVwSOvY1sQBIySrQ1oXGaAHJ4ijiktCxr4kFQEpWbpACiRUj\nSA5HYZeEjn1NLAASX1Yr2T4LSMEEpQEkl6OwS1o79rF/L5FYAKRiag3SEvpwJB/J0m22R7KR\n/vjD7S+mZyOF7G+fniXVBmIIILFlgjSqdPT3H3/8MDJk3VM690cR6S3gkQSpOUhWC7++EEhb\n1OqAjAaSVj9Iq7+1Z4hLWgAkppqDZN32BWLtjJoOFkhKvzrykyRykgMkQbo0SETJ1YmZ7wZH\nK0nae63fReQkB0iCJAKkIqd29MqdCZIyV+x0A8UYIv2gTmcBkJhqDVKZ5e9gWMMGkrLXvg2S\n0NW8zhAAqZBygBTmaAZJOZtIhpW+aSRykgMkQbokSP7tWC9IE0lOOa6lbL7ISQ6QBOmKIAWj\ngzaQDI5okCjntPOgTmoBkJi6HkiR6KAVJJOjCEmI/m5iAZCO6BBI4SrgGkg2RzGQEP3dwAIg\nHdGhRmMhjLYmFBRIQZIQ/d3EAiD5tZUy7vRidprKNRrTQHI5ioNEBeHFD+rcFgCJqdogrUVW\nu+1fS8UajW0ZR98JjoIkLW1d+KsOIrEASMXUDKRevzG0DyRGj6QMIL2yT/BEYgGQiqkRSGav\nCvMkLx0kXqcxvX0LxVGIJPSQbWIBkHxyeryY/ZH2JfYx+oFZ/cWovL4ltY/1aUjuqyKA5JMX\nJE2FEvv00G46sW92RtRPItJbwCMJUl2Q7IaybiuKvgJIypMhO5MEkOoOAZDS1TkJsfoa3qwy\nIBmpfUGQKJJETnKAJEiNPJKzale8ZkMCSKjZUHUIgJQsLR1W20eq0rFPv0ICSKKGAEjJMhv1\nrYveh5e/Ge9JAgnFT2oOAZAKqQRIJkdekLwkiZzkAEmQ7g4kuxwXDRKKn9QbAiAVUolmzK+p\nIKH4SbUhAFIh5QfJ5sgPko8kkZMcIAnSnYFk1GwIg2SQJHKSAyRBAkgslyRykgMkQaoC0rrs\nvQQ2GPtGdoZfdpAcjngg6SSJnOQASZDqgrTdaImy+jsGZa/9bV8hcUHSUo9ETnKAJEgtQHKi\nVvtykQ1GopJes4FF0pp6JHKSAyRBag0SkSKbtYj+K8URH6SFJZGTHCAJkiyQsnTs2+TN7AvK\nzezLdkBQmgCSqVYeyZTmal5eA0I+Ut0h4JHYEgGSfsoGkAQNAZDYOhdISOyrOwRAYqvhqt0q\nYw0BIAkaAiCx1XQfaZK5FhcGCYl9VYcASGwtEQ16ZIN5V393bpCITrIASdAQAKmQ8oI0MPSH\nvTm0guSpLIkM2YpDAKRCyhvZ8MdNzjbrUhN/2KKlezYnDJF+UCeyAEhMXRskpf4gAxYmkJQn\nlgEgVR0CIBVSLpCGSyNP6M+LzhGHJJGTHCAJ0mVBGs7YdI4MXF5ezRejJImc5ABJkFqDROQn\nZQFJvdochUCKkiRykgMkQWoL0gZRXpAUwZFOy0uIMookkZMcIAlSY5DWm5wgTetwDkcaLS+v\n03qddhnlkqR3QRI5yQGSIDUFqSPvHuxqPi9nExxttLyoAaO5u5jy+6SVJZGTHCAJkiyQjuYj\nKRXJPVLrq8rqL3Z7ZjPW7+bLroFSBZB4KuCRFvlaYY7fV73QSw1qluGMvEOkH9QJLeCRmLoo\nSP6WsiMoL/GlBiw21BoCIB1WMZBirZkDC3o0SSInOUASpOuu2gUwInrIRkgSOckBkiBdcB+J\n4Y6YIG0kiZzkAEmQLhfZEHNHvkZjYZJETnKAJEitQSJ0bB/JR8/S1VL5Go0FSRI5yQGSIF0L\nJI87GunR4xjIApEhkkROcoAkSJcCyeuObGYSQJpIEjnJAZIgXQgk79WRGy1ElywOkCRykgMk\nQboSSGyOfLW//SSJnOQASZAuA1KCPxpBMkK/wyDdSBI5yQGSIFUFaatvp93TCnNN2gWSd9Gb\njgLfQr9j+X3Th4ic5ABJkOqC1C03LlKbdoDk3zyiOfrz2yYdJf/HJP9OIrEASMXUCKSZHzM2\naFbqr+epTecF6eaNdJB0lLwf9EKW1g9JJBYAqZgqn9p1y7+ZQJpiuZM4+nE7qzNBuqEUI+ll\nChtPODKRWACkYmoFkvHfquTEPqcnWLy1mJbR5+T2UV3G0HGsnQASLRKkPIsNtKj08XnVznZT\n6+uJQ6Qf1Kks4JGYqr1qt57XkR5pVMYesr5zvVDQKvmLiJzkAEmQmoG0LNhJASlMkshJDpAE\n6cogeTmKxNqh0VjVIQBSsszTOf1fXdlqf/sX8SKxduiPVHMIgJQsEqRiiw37QUJ/pJpDAKRC\nygRSgKN40Kq9ZSRykgMkQbosSCGOfCDp+7Goa1drCIBUSDJAQl27WkMApEIqVWlVCxfigYS6\ndq0PCiAdUUOQrFi7DSWRkxwgCdJFQQpzxAUJ5bgAEleNEvt6Y9Hb3EsqU7LYiAP3guSShCpC\nDS0AEi0nH8mIcVh0HCQqGWInSDNKIic5QBKk64FE5/mZiUl+kDz9xkROcoAkSG0T+7KD5M2W\nZYPkKaefnGsuEguAVEwCQNKSKY527PMm+nka+AWa+iGpT4AAEi0dpG2xwc5KypjYt8j2MlNy\neqi0avIQF7WAR2KqVRpFpz/ZGyTVAWkoxEWfBwKkukMApGTRIBVMNZ/l8LL2kOWSJHKSAyRB\nEgCS9u+oGiCFywYhH6nmEAApWdrSQqc/p99WAUmF1+iQj1RzCICUrEYguRx93+p+81ySyEkO\nkATporF2ugh/pLSqkCySRE5ygCRIlwfJXZlTS+1vxT+5EznJAZIgXROkNRCBWuBea3+HXJJF\nkshJDpAE6XogjeXAX6f2R3TU3VpEn0+SyEkOkATpYiAFO1OsHK1F9NkkiZzkAEmQ6oKk196a\nb3Ou2kUpGhe+AZKsIQBSujrrbpcTJA5GAzl6WxcuSSInOUASpFYgbdHfuSIbAl37Vk3UuCD5\nSELNBoDEVGOQ+jwgedYVXsmOy9/0RmNhktY8JJGTHCAJUjOQtjjVw/lIykoh2jwQmW+U2GFs\nyI+F2gggeWQW+i6TjxS5VLIajQXqffuHSD+o01rAIzHVbLFheyIvSPHlbw9IQZJETnKAJEgC\nQMpbs4HDEQ1SiCSRkxwgCVL7VbucILH2kQyQTJJ0eYZIP6hTWwAkptotNmiPcxWI5HLkA8l8\nKzZk6wwBkNJFRDaMd4037QYpzhHV+pJFkshJDpAE6UKxdnyOeCDpF00iJzlAEiSAxCJJ5CQH\nSIJ0VyDRrS9DduhGUX4IgFRIe2Pt+A7JChwKkoQQoYYWAOmIdoHECP1ea9lNiX2xSkKGUxI5\nyQGSIF0EJAZGmz+ag1ZTSBI5yQGSILUESd9KOpaPxOFodUhr9DebJCVzkgMkQWoIUmdE2R0A\niXNaZzikRJButiInOUASpOYgHc5HUuollSOr+AmHJPRHamEBkDjKANKU0McByeDIBSlG0sur\nE34XkUgsAFIxtQNpPa87kNjnS8bzNhozs/r+1DL/vIl96DXWTgCJIQqkUVkqrRoh3NtFlBVr\nZ4Z+Jw6RflAntIBHYqoZSNsZXQmQFnSsOpFOiJBxRhdASeQkB0iC1A4kvfdlzq7mvX8Zzw0R\nst7oRUnkJAdIgiTAI2UHybdwsK0t0BmyswvjDJF+UCe1AEhMtQLJ2D7Kldg3yZ9gxADJ45ZE\nTnKAJEjXA4nBURgkCiWRkxwgCdJFYu02ec/r9DqREZDQaKzmEACpkA6BFL8+MkHyl1j1DpF+\nUCe2AEhMXQwkLxY/EkFCf6RqQwCkQspdjsup/s0tfkIOkX5Qp7YASExdCiSyQZ9DERskVBFq\nfVAA6YhyluMiMWLXbEAVIYDEVSaQnCJ1RrV8/Zmuc4wtZSx+QmKk90qKkYTiJ+WHAEirOiMf\nwl9D1a39TSlfozGKI7Uk9m0oofhJ0yEA0iqikDddRLUYSGSjMZIjLR+JRdIUNCRykgMkQcoB\nUmc+iIG0eS63ePGgHanm9Gqdxx1piX2Rfn0GS4kSiQVAKqbcINl5ESGQ5vdpT+7r2BfO5fM2\n69Mz+6JpfSXS1qCYAFLw1M4CyA63y5LYF156cEOEIr+DSG8BjyRImUFaSUkByVrLKwUSGbS6\nkYTWl42GAEiLdJAWKoKLDVohrs5+S65U8+AlE7khS7cY8w+RflAntABITGVetWN5pBYgmTuz\n4Q1ZAiWRkxwgCVLefaQNn+A+0gySu9gwKkvNhoA7skEi1uyQj1RxCICkab7K0UAioxisdL5M\ny99HQWKQJHKSAyRBahNrR+TFbsoAUoQjGySKJOQj1RoCIO1XYZBiHDkgkaUbgkOkH9Q5LQAS\nU+VBcmNVO6dKsaH8VYR2gYR8pEpDAKRCyl5FyI0VmkDSY8AjLknkJAdIgnQ9kBgcjSBNcXdM\nkkROcoAkSAVBslbAO+MkT7+1VvdyVxEiQVrCV8Mkoas5QGKqKkjWa537pkGZqwiRqeYLRrFc\nCiT2lR8CIEVkpczqtNihELk2ZFOS+5gkIbGvoQVAGhQHyXnTqN2p5mRakgvS3NXcIclbyguJ\nfa0sANKgTr+jxz3osQwmSPvykSYpMqfIzUpSdlbS+hZvUpJSedNsIKYA0iAXJGNlwQ4qWpUn\njWIS0WxiW/52zunQH6nFEPBIEQU80vZCWZCc9kfa8jdBEkBqMQRAiki/EKJjgiqDRGXIMl2S\nyEkOkASpDUilVu0sKdIduSDFXZLISQ6QBKkKSFqK+fy42D6SLkW7I4AkawiAFJHRJVZ7omxk\ngybl48ifRoEesvWHAEiFlAskjaNAWxceSSInOUASpOuCpBx3tJX8DqRR0D+IyEkOkATpsiC5\n53Vqq67qgBQjSeQkB0iCdFWQfBxNEUEhkLSY7604l8hJDpAE6Q5AWk7stNg6FyQj0m4pcLc8\naD2fGloAJKYuClKAIwZItlBEv5EFQCLkbCv5lLeKkMPRQBIBUrgjxUsySiKxAEjF1AKkLkzS\n8eInLkeHQYrUBo8f1EktABJT1wNJUfuwOkc3kiiQgiS9JJ/gicQCIBVTS5DW8qzZKq0qK7lv\ny37NANLEEvcHE4kFQCqmBiAZWRXdVgO8P5bYN8iX1efN5TMy/mLNxtByrLYAEiEHpOVBiSL6\no7RNVsv5fA9WOkkY4vIW8EhM1QdJiwTXWikVAMnPEUCSNARAStMK0hrvXbCtC710t4EULr7F\nHCL9oM5nAZCYauiROut2Uf5GYwBptwVAYqo6SGa9yM5cbBhVBaREkkROcoAkSBVBMnP4uqmO\nUJd1+XtVmCOAJGkIgJRJ9u5shv5IvqInGkjRTi7hIdIP6pwWAImpK4JkF+Fy916/+zZgkWpe\nfwiAlEm5QYr26wuAhFTz+kMApEI62NaF2x8pySWJnOQASZCuBhKzrcuPRJJETnKAJEjXAonq\nRxEAiU+SyEkOkASpFUhEibtF+0HitXXRQKJJIn4TkZMcIAlSM5DMezn2kcj2SBGQuCsOIic5\nQBKk5iC5NYv3gUS3GaM5ioHkOiWRkxwgCZIUkDTtAMlDkY8jPdU81KdPHyL9oC5hAZCYag+S\nfoW0N7HPm4Wn5iZ9s5Ly+fLnqUGJAkhRmXF32WPtZi2V6Vb3M/ufl/AVUcoQF7eAR2KquUdy\nH+fuj2Sc3k0oGSBxSBI5yQGSIF0fJPsySTkgRUhCpdVmFgApquyrdoRIjkafpIE0Fh7y1wYa\nlzFQabWRBUCKSltsMB72mWs2lU66TwAADaNJREFUOP5Ifbuh8bJhNLPl+R2WNb2X5N9JJBYA\nqZiag5QzskGXojmaW7s4qxA0Seva+AtrSSJ6UOezAEhMXSvWbhOxzvDjh9baZWs65idJ25wC\nSE0sANIR5SiiH+bo25/uRq1Lkr5V+0KH4CUd1CktABJTVwRp9STKwxEFkkuSBRJvw8l7UCe1\nAEhMXQ+k7YTM65C+/fmNckmm0zFih17YW7f0QZ3WAiAxdTWQAnUhtUL6f37zkER+zrbxlPBr\nicQCIBVTG5C6rkg+Et3ShQuS5pOcGNhlvZz/c4nEAiAVUzuPtOzE5ttH8rR0cTkaQKJd0tw/\n9tWWtvGUeFDpX0OUBUBiqj1Ixs2g3Yl95tyPgeQjiZQRCpFyUOlfQ5YFQGKqNUhE7749ILlu\nJMSRDyQ/SWa4OIclkVgApGKSBdLOfCRF5BTZuUd2rzGy3Riz19iLUgWSbyBHAImhrB7JUbhK\npK+uHUoWNxgCHumY2oPkkgSQGgwBkI6pKkjW9ZC3rh1qf9cfAiAdU/ZVO0M7QULJ4vpDAKRj\nyr+PpClSSN9fIBIgVR8CIB0TXUeozxP9HeYoVNcOtb9rDwGQCqktSKj9XXsIgFRIGTr2RTgK\nV1qlfhKRkxwgCdK9g8R0SSInOUASpCuCFG81Fi5ZjG4UVYcASIWUu/VlGCQeSSInOUASpOuB\nxOk1poPEIknkJAdIgtS80dha/3t96WAPWQZHJkgkSSowRPpBndcCIDHVuK5dlxskXtM+EyRG\nB0yRkxwgCVJzkNyYu8w9ZP1dzYMgmU5J5CQHSIJ0IZB83cbiIHn79q0wiZzkAEmQ2oO0/tfv\nbzQ2KtxsLCx0GxMpgBSVXkWoL1NEfxblbV5mh+O7JEoc4sIW8EhMSSii3zcAaar8rRWTPDLE\nhS0AElMCQNKW7kblBcmzkOBcHYV/CJGTHCAJ0tVBojmiglaDv4TISQ6QBEkCSHYpodTPYoCk\ntLqPN3dExtqFfgqRkxwgCdLFQVrY+fHHILV0RaKDVgO/hchJDpAE6XqxdobmPkl//DE3GFPu\nPhLLJYmc5ABJkC4AktJlvTQTstVYVe6GLIckkZMcIAnS2UFSemvlV6uc8HpR9M0iyRf9jbp2\nDYYASIWU8OtN6wdGYW6NJYojAiSOSxI5yQGSIJ0apJkACyRnke7bN5skbxoFCkTWHwIgFRL3\n11vDElyQdKZ+WCANJPmjv1HXrvoQAIkpLdDbDLBbXt9V104LlAuB5HIUBsnT/kjkJAdIglQX\npO0JrTxk36fH2hkZE4kgfVPhNAoKJZGTHCAJUguQ9Lt7an/biUcBkNQPAqRvKpKP5KIkcpID\nJEFqDVJqNwqqw6sfJJojolmfUwnPYknkJAdIgiQLpHhiH7Ol3pbSR3TqI5r1EYl9tZLXIL8A\nkq6Oqhi01yNR8v4fTZF55uPyt+OCdg5xdQt4JKZkeaRR2UBSr36QEkkSOckBkiBdGCT1GgLJ\nWWDYM8T1LQASU61Bytexz45ZDXA0LX+nkCRykgMkQTrpPpKh4Q8xr+VtLKlXgJTBAiAx1Syy\nwbyrv38PSHqQz8hSkKN5QzaBJJGTHCAJ0olj7Vb9ZW8tbQGrQZASSBI5yQGSIF0BJLpOKgMk\nPkkiJzlAEqQLgKS8kQ0+jnxdzQFSiyEAUiGl/XpWhmwiSCGS9Ox1kZMcIAnS2UEaQPCB5OXI\nD9L6c2ghfcOTIic5QBKkxrW/zaW8SSm/HpVqfgCkJbdW2XyJnOQASZDa17VzYhsSUs2n+X4E\nJE9HF+ejkn8nkVgApGI6M0iL3/CA5OcoHaSXZJREYgGQiumsIOmnX4dA4pH08mr0HWNIJBYA\nqZhkgcRuNOZtDOb2F7tN/51NxqgPLZ6CA2kCSFHZiw3aS5miv6egVasNEunDGL+BSG8BjyRI\nsjzSqIwgbW2QQlUeAFLTIQDSERUHyc7qM5a07dqs+4a4BwuAxNSVQbJXG7Ra+/a6xK4h7sEC\nIDF1VZC85RqmVTsnXnzHEHdhAZCYErDYYL+UCaQAR2PNBm68qneIu7AASEydPdZuEAlSiCMq\nQxY1G1oNAZAKKQdIYY7IDNngbqvISQ6QBOmeQXIrFXtjF0ROcoAkSNcEKcKRL0PWT5PISQ6Q\nBAkgUXJQEjnJAZIgXRKkGEe+VHM/SiInOUASpBSQ3FqOnnd1xqOgUYlKq1GOAol9HpRETnKA\nJEhFQGI/S+ogSCq8hcQGyUBJ5CQHSIJ0NZBUOKQhCSQNJZGTHCAJ0i6QuvXWLJY6PJ5P7ZaX\nuunV5XZ515Q+sb2eJ41iCqKLc5SQITsv4omc5ABJkI6BNKOwlO/WHut3++mh+S7z9fkj2Yl9\ntMyMPqYYeX0ZU9WgFF0VJCM+TkfDvaXvWuDQ7V2OXiOFXcwoPY2C9QuI9BbwSIK07xrJ8URa\n/KkfJOtd2ou7y3GNMv4Q7BIMSSSJnOQASZB2LjZ0W28W262EPVJPgNRtnz3o2GIDhyNkyEoa\nAiBlAkm7RhoFkARZACSmjoHkv1YKLTasn2W+vugISDyOkGouaYi7Bmn5x17+7jc6Asvf5lvX\n12cdAInJkVMJD6nmDYe4P5B02edj5Ov71AAkpJo3HAIgiQOJyxFAkjTEPYM0X9IIA4nNEVHk\nGDUbmg1xzyAV1V6Q+BxR1cKNYG+txZgxRPpBnd0CIDEFkByntJW921ASOckBkiBdB6QEjjz9\nK4jikQtKIic5QBKknSB12rr3vKi93O267UnNwP4A/2fvAskpnroDJB9dfev51NACIDG1C6Ru\nXbMzw++2N/T+R1HtASkJoySQRpZkTnKAJEj7QFpvRIDk1vLOC9LilpIkEguAVEx7QOqcu0GQ\num5J9zMT+vS4iP2RDbc5nopFOkhofdnGAiA571/D77QYPC1Sb76i2pHYl9Bu76AKJa9Bft0R\nSO5ig/WOfgNpfYWICs8V/V3IQqS3uP4XvyOQqCcB0nUsABJTAEnKEDItABJTeVbteoB0UQuA\nxFSefaT+KEj5ajaUsRA5ya//xa8OkhbZYDzjW2xYq92RIGVM7CtmIXKSX/+LXx+k7AJIMi0A\nElMCQMI1kmALgMRUQZDI4FXfG7WHAEmQBUBiSoBHsvVfEDSr9VzkSyBIFVThD1RjDuBryBFA\nOu8Q+BqCBJDOOwS+hiABpPMOga8hSPcJEgRlFkCCoAwCSBCUQQAJgjIIIEFQBgEkCMqgewSJ\nE/93eITSgyzJlQWH6ZYRig2y5d0U/5OU1h2CZCYkFhui8Ahb4lepweItRw6P0OtZaeXGqaH7\nA6n49Cj+6eMAWvJJmdG64r/U+vk1/iSlBZCKDVF2gNIgEcU0ygggnVQ1QCp+hVQepHWI0t8F\nIJ1UtTxSjcuwGiCVHKHXL48A0rlU7a9W4TKsAkjO3QKDAKQzCiAlDeHcLTAGQDqjAFLSEM7d\nAkMApDOq2qrdNUAqOkSn3wCkk6nShmyVPd+iAxUfotPvnJujewSpRjxKpeXvGiFC5YbQyrUh\nRAiCoB4gQVAWASQIyiCABEEZBJAgKIMAEgRlEECCoAwCSBCUQQAJgjIIIB2QSv/1nncO9fw0\nDDfrYeeH3PS09wCgsADSAaWD9LDz9/6pfmkgfdz3IYN+qZ/7jSG/ANIBpYO0w4eNevyw3v11\nLCztw+MRa8gngHRA1UD6PDikWU/qy67PmPVLfT5iDnkEkA5oxOL2z0fV3c62Pij1YXr8QXWz\nB/n0oB4+TW/99aCexhOzfrjiUfNblPr5NFrf9KFTjz8Xs+6TNtDD5kY+qw/aC/3zo1KPz665\nPqr5gY8HrrAgrwDSAc0gfRzwGGb0SNL8eJz643PjXTVQ9GEG6eN0qTNh1y1XPeObu8H1PK1m\nk76olaqf5krDp+mTPhnm9qjmB3465tEgWgDpgGaQHn8NE3r8txvR+Np/7YYzqM/b3fH15dRO\nTS9q1g/D49u934dp/zzc+/Wo1gW2D+rrcvfRXCzohlc+m+buqMYHfjVdGpRHAOmAZhS+jP/+\nnJ9Q43x9Hs6onua7j8u7jGskw3q+9vk1oPg0XhH9Gs/JRj2ul0gflX7Gtww2SDe3RzU+8JfC\nckMBAaQDWq6RjH9nVvx3B/18/vhoWW+MrcvcxjiDvtoQ3E4Wn75+Nd5Djqp/4N6VQygk/KgH\ntBukx3Vep4H00P3S33K783G4xOp+AqTWwo96QHtB+l09fHr+GQCJGme0+7w+s3Lx/OFhuEYK\ng0R9GpRT+FEPyAPScF3yrH7frlaerCk9/muD9Ghd5Giar5HGz/Qdh22uj2p8IK6RigggHZAH\npGnR7NlaP5stpjWJL/1X+xrp07C09mFddrs9XhcbPoxsUiEND9P634NjboxqfOAXrNqVEEA6\nIA9I4xXQOGn1HZ3R4kENPuPDfMnyxbC2N4K6daH7y7jP9FGZ1zqDPq8f5NlHmt6mf+BH7COV\nEEA6IN810tMcWHDzAt0aYzA+/vIwgHS72FGPX7STr+nfYQluDU1Qv2sbRmNkwwMB0hTZMJGh\nmVujGh+IyIYiAki5VeJa/jlfzPZP+wIMyiKAlFtFFsUes13XIPq7jABSbhUB6acW/n1IyEcq\nJICUW2W2aZ49K9+p+h0ndmUEkCAogwASBGUQQIKgDAJIEJRBAAmCMgggQVAGASQIyiCABEEZ\nBJAgKIP+P/+cr1aJUSUNAAAAAElFTkSuQmCC",
      "text/plain": [
       "plot without title"
      ]
     },
     "metadata": {
      "image/png": {
       "height": 420,
       "width": 420
      }
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "## ====== 设置与依赖 ======\n",
    "# setwd(\"D:/R work\")  # 如需\n",
    "library(readxl)\n",
    "library(tidyverse)   # dplyr/ggplot2/tidyr/forcats\n",
    "library(Boruta)\n",
    "library(ranger)\n",
    "library(ggridges)\n",
    "library(scales)\n",
    "\n",
    "set.seed(250307)\n",
    "\n",
    "## ====== 读取数据并准备 ======\n",
    "dat <- read_excel(\"Raw_data_MLET.xlsx\")\n",
    "\n",
    "# 排除不参与建模的列\n",
    "drop_cols <- c(\"exercise_tolerance\",\"VO2peak\",\"AT\",\"ATHR\",\"HRmax\",\"VEVCO2Slope\")\n",
    "X <- dat %>% select(-all_of(drop_cols))\n",
    "\n",
    "# 目标变量\n",
    "y <- factor(dat$exercise_tolerance)\n",
    "\n",
    "# 处理：字符转因子；数值缺失用中位数填补（ranger 可混合数值/因子）\n",
    "X <- X %>%\n",
    "  mutate(across(where(is.character), as.factor))\n",
    "for (v in names(X)) {\n",
    "  if (is.numeric(X[[v]]) && anyNA(X[[v]])) {\n",
    "    X[[v]][is.na(X[[v]])] <- median(X[[v]], na.rm = TRUE)\n",
    "  }\n",
    "}\n",
    "\n",
    "df_boruta <- bind_cols(X, outcome = y)\n",
    "\n",
    "## ====== Boruta 特征选择（保留历史以画分布） ======\n",
    "bor <- Boruta(\n",
    "  outcome ~ .,\n",
    "  data       = df_boruta,\n",
    "  pValue     = 0.01,\n",
    "  mcAdj      = TRUE,\n",
    "  maxRuns    = 200,\n",
    "  doTrace    = 2,\n",
    "  holdHistory = TRUE,\n",
    "  getImp     = getImpRfZ\n",
    ")\n",
    "\n",
    "# 打印最终确认变量\n",
    "confirmed <- names(bor$finalDecision)[bor$finalDecision == \"Confirmed\"]\n",
    "cat(\"Boruta confirmed features:\\n\"); print(confirmed)\n",
    "\n",
    "## ====== 组装“重要性历史”用于山脊图 ======\n",
    "imp_history <- as.data.frame(bor$ImpHistory)   # 每轮重要性Z分数\n",
    "shadow_cols <- grep(\"shadow\", names(imp_history), value = TRUE, ignore.case = TRUE)\n",
    "real_cols   <- setdiff(names(imp_history), shadow_cols)\n",
    "\n",
    "# 真实特征的最终决策\n",
    "final_decision <- tibble(\n",
    "  feature  = real_cols,\n",
    "  decision = bor$finalDecision[real_cols] |> as.character()\n",
    ")\n",
    "\n",
    "# 影子特征（仅用于参考，可在图例里区分；如不需要可注释掉）\n",
    "shadow_decision <- tibble(\n",
    "  feature  = shadow_cols,\n",
    "  decision = rep(\"Shadow\", length(shadow_cols))\n",
    ")\n",
    "\n",
    "decision_all <- bind_rows(final_decision, shadow_decision)\n",
    "\n",
    "imp_long <- imp_history %>%\n",
    "  pivot_longer(cols = everything(), names_to = \"feature\", values_to = \"importance\") %>%\n",
    "  filter(is.finite(importance)) %>%\n",
    "  left_join(decision_all, by = \"feature\")\n",
    "\n",
    "# y 轴顺序：按真实特征的中位重要性从小到大（影子放最下方）\n",
    "order_tbl <- imp_long %>%\n",
    "  filter(feature %in% real_cols) %>%\n",
    "  group_by(feature) %>% summarise(med = median(importance, na.rm = TRUE)) %>%\n",
    "  arrange(med)\n",
    "\n",
    "imp_long <- imp_long %>%\n",
    "  mutate(feature = fct_relevel(feature, c(order_tbl$feature, setdiff(unique(feature), order_tbl$feature))))\n",
    "\n",
    "## ====== 山脊图（无标题）并保存高清 ======\n",
    "p_ridge <- ggplot(imp_long %>% filter(feature %in% real_cols),  # 只画真实特征\n",
    "                  aes(x = importance, y = feature, fill = decision)) +\n",
    "  geom_density_ridges_gradient(scale = 3, rel_min_height = 0.01, color = \"black\", size = 0.2) +\n",
    "  scale_fill_manual(values = c(\"Confirmed\" = alpha(\"#02BBC1\",0.7),\n",
    "                               \"Tentative\" = alpha(\"#FFC107\",0.7),\n",
    "                               \"Rejected\"  = alpha(\"#E53935\",0.7),\n",
    "                               \"Shadow\"    = alpha(\"#757575\",0.6))) +\n",
    "  labs(x = \"Importance (Z-score)\", y = \"Features\") +  # 无标题\n",
    "  theme_bw(base_size = 12) +\n",
    "  theme(legend.position = \"right\",\n",
    "        panel.spacing   = unit(0.1, \"lines\"),\n",
    "        axis.text.y     = element_text(size = 9))\n",
    "\n",
    "print(p_ridge)\n",
    "ggsave(\"Boruta_RidgePlot.png\", p_ridge, width = 8, height = 10, dpi = 600)\n",
    "ggsave(\"Boruta_RidgePlot.pdf\", p_ridge, width = 8, height = 10)\n",
    "\n",
    "# （如需包含 Shadow 分布，把上面过滤里的 %>% filter(feature %in% real_cols) 去掉）\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "f5347509-603d-4b48-b5a8-e835df054423",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<strong>png:</strong> 2"
      ],
      "text/latex": [
       "\\textbf{png:} 2"
      ],
      "text/markdown": [
       "**png:** 2"
      ],
      "text/plain": [
       "png \n",
       "  2 "
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<strong>png:</strong> 2"
      ],
      "text/latex": [
       "\\textbf{png:} 2"
      ],
      "text/markdown": [
       "**png:** 2"
      ],
      "text/plain": [
       "png \n",
       "  2 "
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<strong>png:</strong> 2"
      ],
      "text/latex": [
       "\\textbf{png:} 2"
      ],
      "text/markdown": [
       "**png:** 2"
      ],
      "text/plain": [
       "png \n",
       "  2 "
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<strong>png:</strong> 2"
      ],
      "text/latex": [
       "\\textbf{png:} 2"
      ],
      "text/markdown": [
       "**png:** 2"
      ],
      "text/plain": [
       "png \n",
       "  2 "
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "[LASSO @ lambda.min]\n",
      "Retained variables: 15 \n",
      "      feature          beta\n",
      "      Smoking  9.462544e-01\n",
      "       Gender  6.415778e-01\n",
      "     Diabetes  5.964867e-01\n",
      "          RBC -4.669203e-01\n",
      "          BMI  1.065463e-01\n",
      "           PV -7.228664e-02\n",
      "          Age  5.176422e-02\n",
      "     CAD_Type  3.804825e-02\n",
      "          RHR  3.505657e-02\n",
      " Hypertension  3.272457e-02\n",
      "          MPA  1.903287e-02\n",
      "           Hb -1.865654e-02\n",
      "        AOasc  1.236296e-02\n",
      "           SV -2.375593e-03\n",
      "           CO -5.668679e-05\n",
      "\n",
      "[LASSO @ lambda.1se]\n",
      "Retained variables: 8 \n",
      "  feature        beta\n",
      "  Smoking  0.49157330\n",
      " Diabetes  0.45166651\n",
      "      RBC -0.25323580\n",
      "   Gender  0.22549943\n",
      "      BMI  0.05118241\n",
      "      Age  0.03709311\n",
      "      RHR  0.02692268\n",
      "       Hb -0.01807385\n"
     ]
    }
   ],
   "source": [
    "# ==== Packages ====\n",
    "library(readxl)\n",
    "library(glmnet)\n",
    "\n",
    "# ==== Data ====\n",
    "df <- read_excel(\"Raw_data_MLET.xlsx\")\n",
    "drop_cols <- c(\"exercise_tolerance\",\"VO2peak\",\"AT\",\"ATHR\",\"HRmax\",\"VEVCO2Slope\")\n",
    "y <- as.factor(df$exercise_tolerance)\n",
    "X <- df[, setdiff(names(df), drop_cols), drop = FALSE]\n",
    "\n",
    "# 简单缺失处理：数值-中位数；非数值-众数并转因子\n",
    "for (nm in names(X)) {\n",
    "  if (is.numeric(X[[nm]])) {\n",
    "    if (anyNA(X[[nm]])) X[[nm]][is.na(X[[nm]])] <- median(X[[nm]], na.rm = TRUE)\n",
    "  } else {\n",
    "    X[[nm]] <- as.factor(X[[nm]])\n",
    "    if (anyNA(X[[nm]])) {\n",
    "      tb <- table(X[[nm]]); mode_val <- names(which.max(tb))\n",
    "      X[[nm]][is.na(X[[nm]])] <- mode_val\n",
    "    }\n",
    "  }\n",
    "}\n",
    "# 模型矩阵（哑变量；无截距）\n",
    "Xmm <- model.matrix(~ . - 1, data = X)\n",
    "\n",
    "# ==== LASSO with 10-fold CV ====\n",
    "set.seed(123)\n",
    "cvfit <- cv.glmnet(Xmm, y, family = \"binomial\", alpha = 1, nfolds = 10)\n",
    "fit <- cvfit$glmnet.fit\n",
    "lam_min <- cvfit$lambda.min\n",
    "lam_1se <- cvfit$lambda.1se\n",
    "\n",
    "# ==== 保存：系数路径图（无标题） ====\n",
    "png(\"LASSO_Coefficient_Path.png\", width = 2000, height = 1600, res = 300)\n",
    "plot(fit, xvar = \"lambda\", main = \"\")\n",
    "abline(v = log(lam_min), lty = 2)\n",
    "abline(v = log(lam_1se), lty = 2)\n",
    "dev.off()\n",
    "\n",
    "pdf(\"LASSO_Coefficient_Path.pdf\", width = 8, height = 6)\n",
    "plot(fit, xvar = \"lambda\", main = \"\")\n",
    "abline(v = log(lam_min), lty = 2)\n",
    "abline(v = log(lam_1se), lty = 2)\n",
    "dev.off()\n",
    "\n",
    "# ==== 保存：CV 曲线（无标题） ====\n",
    "png(\"LASSO_CV_Curve.png\", width = 2000, height = 1600, res = 300)\n",
    "plot(cvfit, main = \"\")\n",
    "abline(v = log(lam_min), lty = 3)\n",
    "abline(v = log(lam_1se), lty = 3)\n",
    "dev.off()\n",
    "\n",
    "pdf(\"LASSO_CV_Curve.pdf\", width = 8, height = 6)\n",
    "plot(cvfit, main = \"\")\n",
    "abline(v = log(lam_min), lty = 3)\n",
    "abline(v = log(lam_1se), lty = 3)\n",
    "dev.off()\n",
    "\n",
    "# λ.min\n",
    "co_min <- coef(cvfit, s = \"lambda.min\")\n",
    "nm_min <- rownames(co_min)\n",
    "b_min  <- as.numeric(co_min)\n",
    "idx_min <- which(b_min != 0 & nm_min != \"(Intercept)\")\n",
    "keep_min <- nm_min[idx_min]\n",
    "tbl_min <- data.frame(feature = keep_min, beta = b_min[idx_min])\n",
    "tbl_min <- tbl_min[order(-abs(tbl_min$beta)), ]\n",
    "\n",
    "cat(\"\\n[LASSO @ lambda.min]\\n\")\n",
    "cat(\"Retained variables:\", length(keep_min), \"\\n\")\n",
    "print(tbl_min, row.names = FALSE)\n",
    "write.csv(tbl_min, \"LASSO_features_lambda_min.csv\", row.names = FALSE)\n",
    "\n",
    "# λ.1se\n",
    "co_1se <- coef(cvfit, s = \"lambda.1se\")\n",
    "nm_1se <- rownames(co_1se)\n",
    "b_1se  <- as.numeric(co_1se)\n",
    "idx_1se <- which(b_1se != 0 & nm_1se != \"(Intercept)\")\n",
    "keep_1se <- nm_1se[idx_1se]\n",
    "tbl_1se <- data.frame(feature = keep_1se, beta = b_1se[idx_1se])\n",
    "tbl_1se <- tbl_1se[order(-abs(tbl_1se$beta)), ]\n",
    "\n",
    "cat(\"\\n[LASSO @ lambda.1se]\\n\")\n",
    "cat(\"Retained variables:\", length(keep_1se), \"\\n\")\n",
    "print(tbl_1se, row.names = FALSE)\n",
    "write.csv(tbl_1se, \"LASSO_features_lambda_1se.csv\", row.names = FALSE)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "57fcb339-63ed-4622-b30c-5764116b43ab",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "lambda.min = 0.01784718 \n",
      "lambda.1se = 0.0375666 \n",
      "Variables retained at lambda.min: 15 \n",
      "        feature          beta\n",
      "1      Diabetes  5.964867e-01\n",
      "2        Gender  6.415778e-01\n",
      "3           Age  5.176422e-02\n",
      "4           BMI  1.065463e-01\n",
      "5      CAD_Type  3.804825e-02\n",
      "6         AOasc  1.236296e-02\n",
      "7           MPA  1.903287e-02\n",
      "8            SV -2.375593e-03\n",
      "9            CO -5.668679e-05\n",
      "10           PV -7.228664e-02\n",
      "11          RHR  3.505657e-02\n",
      "12          RBC -4.669203e-01\n",
      "13           Hb -1.865654e-02\n",
      "14      Smoking  9.462544e-01\n",
      "15 Hypertension  3.272457e-02\n",
      "Variables retained at lambda.1se: 8 \n",
      "   feature        beta\n",
      "1 Diabetes  0.45166651\n",
      "2   Gender  0.22549943\n",
      "3      Age  0.03709311\n",
      "4      BMI  0.05118241\n",
      "5      RHR  0.02692268\n",
      "6      RBC -0.25323580\n",
      "7       Hb -0.01807385\n",
      "8  Smoking  0.49157330\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<strong>png:</strong> 2"
      ],
      "text/latex": [
       "\\textbf{png:} 2"
      ],
      "text/markdown": [
       "**png:** 2"
      ],
      "text/plain": [
       "png \n",
       "  2 "
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<strong>png:</strong> 2"
      ],
      "text/latex": [
       "\\textbf{png:} 2"
      ],
      "text/markdown": [
       "**png:** 2"
      ],
      "text/plain": [
       "png \n",
       "  2 "
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "## ==== Packages ====\n",
    "library(readxl)\n",
    "library(glmnet)\n",
    "\n",
    "## ==== Data ====\n",
    "df <- read_excel(\"Raw_data_MLET.xlsx\")\n",
    "drop_cols <- c(\"exercise_tolerance\",\"VO2peak\",\"AT\",\"ATHR\",\"HRmax\",\"VEVCO2Slope\")\n",
    "y <- as.factor(df$exercise_tolerance)\n",
    "X <- df[, setdiff(names(df), drop_cols), drop = FALSE]\n",
    "\n",
    "# 缺失值处理：数值=中位数，非数值=众数\n",
    "for (nm in names(X)) {\n",
    "  if (is.numeric(X[[nm]])) {\n",
    "    if (anyNA(X[[nm]])) X[[nm]][is.na(X[[nm]])] <- median(X[[nm]], na.rm = TRUE)\n",
    "  } else {\n",
    "    X[[nm]] <- as.factor(X[[nm]])\n",
    "    if (anyNA(X[[nm]])) {\n",
    "      tb <- table(X[[nm]]); mode_val <- names(which.max(tb))\n",
    "      X[[nm]][is.na(X[[nm]])] <- mode_val\n",
    "    }\n",
    "  }\n",
    "}\n",
    "\n",
    "# 模型矩阵（哑变量，无截距）\n",
    "Xmm <- model.matrix(~ . - 1, data = X)\n",
    "\n",
    "## ==== LASSO with 10-fold CV ====\n",
    "set.seed(123)\n",
    "cvfit <- cv.glmnet(Xmm, y, family = \"binomial\", alpha = 1, nfolds = 10)\n",
    "fit <- cvfit$glmnet.fit\n",
    "\n",
    "lam_min <- cvfit$lambda.min\n",
    "lam_1se <- cvfit$lambda.1se\n",
    "\n",
    "cat(\"lambda.min =\", lam_min, \"\\n\")\n",
    "cat(\"lambda.1se =\", lam_1se, \"\\n\")\n",
    "\n",
    "## ==== 提取非零变量 ====\n",
    "get_nonzero <- function(model, s) {\n",
    "  co <- coef(model, s = s)\n",
    "  nm <- rownames(co)\n",
    "  b  <- as.numeric(co)\n",
    "  idx <- which(b != 0 & nm != \"(Intercept)\")\n",
    "  data.frame(feature = nm[idx], beta = b[idx])\n",
    "}\n",
    "\n",
    "# lambda.min\n",
    "tbl_min <- get_nonzero(cvfit, s = \"lambda.min\")\n",
    "cat(\"Variables retained at lambda.min:\", nrow(tbl_min), \"\\n\")\n",
    "print(tbl_min)\n",
    "\n",
    "# lambda.1se\n",
    "tbl_1se <- get_nonzero(cvfit, s = \"lambda.1se\")\n",
    "cat(\"Variables retained at lambda.1se:\", nrow(tbl_1se), \"\\n\")\n",
    "print(tbl_1se)\n",
    "\n",
    "# 保存结果\n",
    "write.csv(tbl_min, \"LASSO_features_lambda_min.csv\", row.names = FALSE)\n",
    "write.csv(tbl_1se, \"LASSO_features_lambda_1se.csv\", row.names = FALSE)\n",
    "\n",
    "## ==== 图像保存 ====\n",
    "# A. 系数路径图\n",
    "png(\"LASSO_Coefficient_Path.png\", width = 2400, height = 1800, res = 600)\n",
    "plot(fit, xvar = \"lambda\", main = \"\")\n",
    "abline(v = log(lam_min), lty = 2)\n",
    "abline(v = log(lam_1se), lty = 2)\n",
    "dev.off()\n",
    "\n",
    "# B. CV 曲线\n",
    "png(\"LASSO_CV_Curve.png\", width = 2400, height = 1800, res = 600)\n",
    "plot(cvfit, main = \"\")\n",
    "abline(v = log(lam_min), lty = 3)\n",
    "abline(v = log(lam_1se), lty = 3)\n",
    "dev.off()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "5c5070ac-0558-4bf2-a3ec-8bb68697b543",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Warning message:\n",
      "\"package 'car' was built under R version 4.4.3\"\n",
      "Loading required package: carData\n",
      "\n",
      "Warning message:\n",
      "\"package 'carData' was built under R version 4.4.3\"\n"
     ]
    },
    {
     "ename": "ERROR",
     "evalue": "Error in eval(expr, envir, enclos): object 'Xmm' not found\n",
     "output_type": "error",
     "traceback": [
      "Error in eval(expr, envir, enclos): object 'Xmm' not found\nTraceback:\n",
      "1. as.data.frame(Xmm)"
     ]
    }
   ],
   "source": [
    "# ==== Packages for VIF ====\n",
    "library(car)\n",
    "\n",
    "# ==== VIF computation (based on linear model without regularization) ====\n",
    "# 注意：VIF 应用于数值型自变量，若使用 one-hot 编码后的 Xmm 也可直接计算\n",
    "X_df <- as.data.frame(Xmm)\n",
    "\n",
    "# 生成临时响应变量（数值型），因为 car::vif 要求用 lm 拟合\n",
    "# 若你想基于 logistic 回归计算 VIF，可用 rms::vif() 或自己循环拟合\n",
    "set.seed(123)\n",
    "dummy_y <- rnorm(nrow(X_df))  # 模拟响应变量，重点是提取 X 间多重共线性结构\n",
    "\n",
    "# 拟合线性模型用于计算 VIF\n",
    "lm_model <- lm(dummy_y ~ ., data = X_df)\n",
    "vif_values <- vif(lm_model)\n",
    "\n",
    "# 输出按 VIF 大小排序的结果\n",
    "vif_table <- sort(vif_values, decreasing = TRUE)\n",
    "print(round(vif_table, 3))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "724b3eb6-41cc-4454-aeeb-21dd4493ad26",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Warning message:\n",
      "\"package 'readxl' was built under R version 4.4.3\"\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "        Weight            BMI          LVEDD             SV            ESV \n",
      "       157.351        108.221        105.950         55.961         50.363 \n",
      "        Height             CO            EDV            MVE             EA \n",
      "        48.785         16.957         16.080         15.178         14.700 \n",
      "            CI          LVESD             Ee            MVA             FS \n",
      "        14.337         12.014         10.630         10.512          9.220 \n",
      "            Hb            RBC             el            HCT             es \n",
      "         5.819          5.367          4.841          4.615          3.329 \n",
      "        Gender            AOs            MCV          AOasc            Age \n",
      "         2.811          2.023          2.004          1.959          1.915 \n",
      "          IVSd           LAap             TC       CAD_Type            MPA \n",
      "         1.837          1.584          1.560          1.541          1.403 \n",
      "         LVPWd        Smoking           LDLC             TG            RHR \n",
      "         1.370          1.357          1.343          1.334          1.322 \n",
      "          HDLC Hyperlipidemia    CPET_timing       Diabetes   Hypertension \n",
      "         1.295          1.286          1.272          1.218          1.213 \n",
      "            CK             EF             PV             AV            AOa \n",
      "         1.148          1.145          1.141          1.124          1.065 \n"
     ]
    }
   ],
   "source": [
    "# ==== Packages ====\n",
    "library(readxl)\n",
    "library(car)\n",
    "\n",
    "# ==== Load & prepare ====\n",
    "df <- read_excel(\"Raw_data_MLET.xlsx\")\n",
    "drop_cols <- c(\"exercise_tolerance\",\"VO2peak\",\"AT\",\"ATHR\",\"HRmax\",\"VEVCO2Slope\")\n",
    "X <- df[, setdiff(names(df), drop_cols), drop = FALSE]\n",
    "\n",
    "# 简单缺失处理\n",
    "for (nm in names(X)) {\n",
    "  if (is.numeric(X[[nm]])) {\n",
    "    if (anyNA(X[[nm]])) X[[nm]][is.na(X[[nm]])] <- median(X[[nm]], na.rm = TRUE)\n",
    "  } else {\n",
    "    X[[nm]] <- as.factor(X[[nm]])\n",
    "    if (anyNA(X[[nm]])) {\n",
    "      tb <- table(X[[nm]]); mode_val <- names(which.max(tb))\n",
    "      X[[nm]][is.na(X[[nm]])] <- mode_val\n",
    "    }\n",
    "  }\n",
    "}\n",
    "\n",
    "# 模型矩阵（one-hot编码）\n",
    "Xmm <- model.matrix(~ . - 1, data = X)\n",
    "X_df <- as.data.frame(Xmm)\n",
    "\n",
    "# ==== VIF ====\n",
    "set.seed(123)\n",
    "dummy_y <- rnorm(nrow(X_df))  # 随机响应变量\n",
    "lm_model <- lm(dummy_y ~ ., data = X_df)\n",
    "vif_values <- vif(lm_model)\n",
    "vif_table <- sort(vif_values, decreasing = TRUE)\n",
    "print(round(vif_table, 3))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "08a0f3ac-773a-40b3-865e-03d6977580d2",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "      Hb      RBC   Gender  Smoking      Age      RHR      BMI Diabetes \n",
      "   3.106    2.904    1.573    1.269    1.206    1.107    1.103    1.075 \n"
     ]
    }
   ],
   "source": [
    "# ==== 提取子集变量 ====\n",
    "vars_to_keep <- c(\"Age\", \"BMI\", \"Diabetes\", \"Gender\", \"Hb\", \"RBC\", \"RHR\", \"Smoking\")\n",
    "sub_df <- X[, vars_to_keep]\n",
    "\n",
    "# ==== One-hot 编码并去除截距 ====\n",
    "Xmm_sub <- model.matrix(~ . - 1, data = sub_df)\n",
    "Xmm_sub <- as.data.frame(Xmm_sub)\n",
    "\n",
    "# ==== 计算 VIF ====\n",
    "library(car)\n",
    "set.seed(123)\n",
    "dummy_y <- rnorm(nrow(Xmm_sub))\n",
    "lm_model <- lm(dummy_y ~ ., data = Xmm_sub)\n",
    "vif_values <- vif(lm_model)\n",
    "\n",
    "# 排序输出\n",
    "vif_table <- sort(vif_values, decreasing = TRUE)\n",
    "print(round(vif_table, 3))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2aff2857-488e-45c8-9778-ccc5750f2ccd",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "R",
   "language": "R",
   "name": "ir"
  },
  "language_info": {
   "codemirror_mode": "r",
   "file_extension": ".r",
   "mimetype": "text/x-r-source",
   "name": "R",
   "pygments_lexer": "r",
   "version": "4.4.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
